apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcps-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcps
  template:
    metadata:
      labels:
        app: mcps
    spec:
      containers:
        - name: mcps
          image: uwc/mcps
          env:
            - name: MYSQL_URL
              value: "mysql://root:password123@mcps-mysql-srv:3306"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq-srv:5672"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: google-id-secret
                  key: GOOGLE_ID
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: GOOGLE_SECRET
            - name: COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-key-secret
                  key: COOKIE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: mcps-srv
spec:
  selector:
    app: mcps
  ports:
    - name: mcps
      protocol: TCP
      port: 3000
      targetPort: 3000
