apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: uwc/users
          env:
            - name: MONGO_URL
              value: "mongodb://users-mongo-srv:27017/users"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: google-id-secret
                  key: GOOGLE_ID
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: GOOGLE_SECRET
            - name: COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-key-secret
                  key: COOKIE_KEY
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-recret-key-secret
                  key: AWS_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: users-srv
spec:
  selector:
    app: users
  ports:
    - name: users
      protocol: TCP
      port: 3000
      targetPort: 3000
