apiVersion: skaffold/v3
kind: Config
metadata:
  name: UWC
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: tiket-372908
  artifacts:
    - image: us.gcr.io/tiket-372908/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.gcr.io/tiket-372908/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: us.gcr.io/tiket-372908/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
