apiVersion: skaffold/v3
kind: Config
metadata:
  name: uwc
build:
  # local:
  #   push: false
  # googleCloudBuild:
  #   projectId: tiket-372908
  artifacts:
    - image: uwc/user
      context: users-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: uwc/client
      context: client-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    # - image: uwc/client
    #   context: client
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "**/*.js"
    #         dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
