apiVersion: skaffold/v3
kind: Config
metadata:
  name: 803635532235.dkr.ecr.ap-southeast-1.amazonaws.com/uwc
build:
  # local:
  #   push: false
  # googleCloudBuild:
  #   projectId: tiket-372908
  artifacts:
    - image: 803635532235.dkr.ecr.ap-southeast-1.amazonaws.com/uwc:users
      context: users-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: 803635532235.dkr.ecr.ap-southeast-1.amazonaws.com/uwc:client
      context: client-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: 803635532235.dkr.ecr.ap-southeast-1.amazonaws.com/uwc:mcps
      context: mcps-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: 803635532235.dkr.ecr.ap-southeast-1.amazonaws.com/uwc:rabbitmq
      context: rabbitmq-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: 803635532235.dkr.ecr.ap-southeast-1.amazonaws.com/uwc:redis
      context: redis-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: 803635532235.dkr.ecr.ap-southeast-1.amazonaws.com/uwc:route
      context: route-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: 803635532235.dkr.ecr.ap-southeast-1.amazonaws.com/uwc:vehicles
      context: vehicles-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
