apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: 803635532235.dkr.ecr.ap-southeast-1.amazonaws.com/uwc:rabbitmq
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
              value: "mongodb://rabbitmq-mongo-srv:27017/rabbitmq"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: google-id-secret
                  key: GOOGLE_ID
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: GOOGLE_SECRET
            - name: COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-key-secret
                  key: COOKIE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-srv
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 3000
      targetPort: 3000
