apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: 803635532235.dkr.ecr.ap-southeast-1.amazonaws.com/uwc:redis
          env:
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: google-id-secret
                  key: GOOGLE_ID
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: GOOGLE_SECRET
            - name: COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-key-secret
                  key: COOKIE_KEY
