# name: deploy

# on:
#   push:
#     branches: ["main"]
#     paths:
#       - "infra/k8s/k8s-prod/**"

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Install kubectl
#         uses: azure/setup-kubectl@v3
#         with:
#           version: "v.21.3" # default is latest stable
#         id: install
#       - name: Deploy docker image from ECR to EKS
#         run: kubectl apply -f infra/k8s/k8s-prod

name: Deploy to EKS

on:
  push:
    branches:
      - main
    paths:
      - "infra/k8s/k8s-prod/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Apply Kubernetes manifests
        uses: steebchen/kubectl@master
        with:
          command: apply -f infra/k8s/k8s-prod
