name: deploy-mcps

on:
  push:
    branches: ["main"]
    paths:
      - "mcps-service/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd mcps-service && docker build -t 803635532235.dkr.ecr.ap-southeast-1.amazonaws.com/uwc:mcps .
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: uwc
          IMAGE_TAG: ${{ github.sha }}
        run: docker push 803635532235.dkr.ecr.ap-southeast-1.amazonaws.com/uwc:mcps
