name: deploy

on:
  push:
    branches: ["main"]
    paths:
      - "infra/k8s/k8s-prod/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v.21.3" # default is latest stable
        id: install
      - name: Deploy docker image from ECR to EKS
        run: kubectl apply -f infra/k8s/k8s-prod
